
/* -----------------------------------------------------
   Overall Statistics
   ----------------------------------------------------- */

/* Calculate total sales across all order items */
SELECT SUM(sales) AS total_sales
FROM order_items;

/* Calculate total profit across all order items */
SELECT SUM(profit) AS total_profit
FROM order_items;

/* Calculate total quantity sold across all order items */
SELECT SUM(quantity) AS total_quantity
FROM order_items;

/* Calculate average sales value per order item */
SELECT AVG(sales) AS average_sales
FROM order_items;

/* Calculate average profit per order item */
SELECT AVG(profit) AS average_profit
FROM order_items;

/* Find the highest sales value recorded */
SELECT MAX(sales) AS highest_sale
FROM order_items;

/* Find the lowest sales value recorded */
SELECT MIN(sales) AS lowest_sale
FROM order_items;


/* -----------------------------------------------------
   GROUP BY Examples
   ----------------------------------------------------- */

/* Count the number of customers in each segment */
SELECT
    segment,
    COUNT(*) AS total_customers
FROM customers
GROUP BY segment;

/* Calculate total sales for each product category */
SELECT
    p.category,
    SUM(oi.sales) AS total_sales
FROM products p
JOIN order_items oi
    ON p.product_id = oi.product_id
GROUP BY p.category;

/* Calculate total profit generated by each region */
SELECT
    o.region,
    SUM(oi.profit) AS total_profit
FROM orders o
JOIN order_items oi
    ON o.order_id = oi.order_id
GROUP BY o.region;